# Generated by Django 5.2.4 on 2025-08-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agents",
            "0002_agent_agent_type_alter_agent_form_schema_chatsession_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Session expiration time (2 hours from last activity)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("abandoned", "Abandoned"),
                    ("failed", "Failed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
