# Generated by Django 5.2.4 on 2025-08-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_chatsession_expires_at_alter_chatsession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="message_limit",
            field=models.IntegerField(
                default=50,
                help_text="Maximum messages per chat session (for chat agents)",
            ),
        ),
    ]
