# Generated by Django 5.2.4 on 2025-08-04 11:05

from django.db import migrations


def fake_migration(apps, schema_editor):
    """
    Fake migration - Railway database already has access_url_name and display_url_name columns
    but Django model didn't have them defined. Now model has fields, so we just need to 
    mark this migration as applied without doing anything.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_add_message_limit"),
    ]

    operations = [
        migrations.RunPython(fake_migration, fake_migration),
    ]
