# Generated by Django 5.2.4 on 2025-08-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_auto_20250804_1105"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="access_url_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL name for direct access agents",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="display_url_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL name for agent display page",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Session expiration time (30 minutes from last activity)",
                null=True,
            ),
        ),
    ]
