# Generated by Django 5.2.4 on 2025-08-14 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_agent_access_url_name_agent_display_url_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="category",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="agentexecution",
            name="agent",
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="agent_name",
            field=models.CharField(
                default="Unknown Agent",
                help_text="Agent name for display purposes",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="agent_slug",
            field=models.SlugField(
                default="unknown",
                help_text="Agent identifier from JSON config",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="agent_name",
            field=models.CharField(
                default="Unknown Agent",
                help_text="Agent name for display purposes",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="agent_slug",
            field=models.SlugField(
                default="unknown",
                help_text="Agent identifier from JSON config",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["agent_slug", "-created_at"],
                name="agents_agen_agent_s_9830ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["user", "-created_at"], name="agents_agen_user_id_f7e09d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["status", "-created_at"], name="agents_agen_status_245b5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["agent_slug", "-created_at"],
                name="agents_chat_agent_s_6def7d_idx",
            ),
        ),
        migrations.DeleteModel(
            name="AgentCategory",
        ),
        migrations.DeleteModel(
            name="Agent",
        ),
    ]
