# Generated by Django 5.2.4 on 2025-08-16 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_remove_agent_category_remove_chatsession_agent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "message_type"],
                name="agents_chat_session_d4ca15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["agent_slug", "user", "status"],
                name="agents_chat_agent_s_4d543e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["status", "expires_at"], name="agents_chat_status_da63b0_idx"
            ),
        ),
    ]
