# Generated by Django 5.2.4 on 2025-08-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_email_verified_emailverificationtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_verified",
        ),
        migrations.DeleteModel(
            name="EmailVerificationToken",
        ),
    ]
