# Generated by Django 5.2.4 on 2025-07-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
