# Generated by Django 5.2.4 on 2025-08-16 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_wallettransaction_stripe_payment_intent_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="wallet_wall_user_id_801842_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["type", "-created_at"], name="wallet_wall_type_18698d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["stripe_session_id"], name="wallet_wall_stripe__789550_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["user", "type"], name="wallet_wall_user_id_8df1fd_idx"
            ),
        ),
    ]
